defmodule BaileysEx.Util.LTHashTest do
  use ExUnit.Case, async: true

  alias BaileysEx.Util.LTHash

  # Deterministic 32-byte value MACs matching the Node.js vector generator.
  # SHA-256("value_mac_a"), SHA-256("value_mac_b")
  @mac_a Base.decode16!("ABA8B9C205E5542477C5EBA406BC266DAE3544D73ADD097CBBAC08D2B36967C7")
  @mac_b Base.decode16!("9B94D218F15F2C92A8177663AB394BD482E022206D7079207BC055402CB8BF16")

  # Cross-language pinned vectors generated by the Node.js LTHash implementation.
  # See dev/scripts/generate_syncd_vectors.mjs
  @pinned_after_add_a Base.decode16!(
                        "5C9685D63228E2F99D3E14F51A1015CD89253466915B9D569712D6E408A2F885084F4FA440788CD185D264BE2B03AA4B7AED8D31B894E6E39993556D1C6A6924520847B8A4393A9FC2AF208E8709B2B549A3E6B087D8E4CFFE021E59C8EA002BCB1A64FEB57C8C5EA160AA271D549E991E827994394453D5636120283500B1D5"
                      )
  @pinned_after_add_ab Base.decode16!(
                         "B2A667C07F26C13849DFEA3CC9937F812D08E500ED613E242DB6E34EE5E2470CFDAE1DFF9654F0176A5310185EFA46FE4DD4A85CB019E0D32EA8E8FF3894ACD93AA89DE656B9111F31C387983323158A82ED63CA96D41658563B6138403FCE04E7DFDBD937E974D5D3B1A2216F25BEB3BC85E1F35FF1EC1F662516D605D7867B"
                       )
  @pinned_after_replace Base.decode16!(
                          "5610E2E94DFEDF3EACA0D647AF836AB4A4E2B19A5C06A1CD96A30D6ADD404F86F55FCE5A56DC6446E580AC5933F79CB2D3E61B2BF884FAEF951493921C2A43B5E89F562EB27FD77F6F13670AAC1963D4394A7D190FFC3288583843DF7854CED91CC577DB826CE8763251F8F952D1201A9E03685F26AD994A03C4F6ADD0D6D5A5"
                        )

  describe "new/0" do
    test "returns 128 zero bytes" do
      hash = LTHash.new()
      assert byte_size(hash) == 128
      assert hash == <<0::1024>>
    end
  end

  describe "subtract_then_add/3" do
    test "pinned vector — adding single value to zero hash" do
      result = LTHash.subtract_then_add(LTHash.new(), [], [@mac_a])
      assert result == @pinned_after_add_a
    end

    test "pinned vector — adding two values to zero hash" do
      result = LTHash.subtract_then_add(LTHash.new(), [], [@mac_a, @mac_b])
      assert result == @pinned_after_add_ab
    end

    test "pinned vector — adding then subtracting same value returns to zero" do
      after_add = LTHash.subtract_then_add(LTHash.new(), [], [@mac_a])
      result = LTHash.subtract_then_add(after_add, [@mac_a], [])
      assert result == <<0::1024>>
    end

    test "pinned vector — replacing A with B" do
      after_a = LTHash.subtract_then_add(LTHash.new(), [], [@mac_a])
      result = LTHash.subtract_then_add(after_a, [@mac_a], [@mac_b])
      assert result == @pinned_after_replace
    end

    test "order of additions does not matter (commutative)" do
      hash = LTHash.new()
      result_ab = LTHash.subtract_then_add(hash, [], [@mac_a, @mac_b])
      result_ba = LTHash.subtract_then_add(hash, [], [@mac_b, @mac_a])
      assert result_ab == result_ba
    end

    test "multiple additions accumulate identically to batch" do
      hash = LTHash.new()
      step1 = LTHash.subtract_then_add(hash, [], [@mac_a])
      step2 = LTHash.subtract_then_add(step1, [], [@mac_b])
      both = LTHash.subtract_then_add(hash, [], [@mac_a, @mac_b])
      assert step2 == both
    end

    test "empty sub and add buffers returns unchanged hash" do
      hash = LTHash.subtract_then_add(LTHash.new(), [], [@mac_a])
      assert LTHash.subtract_then_add(hash, [], []) == hash
    end
  end
end
