defmodule BaileysEx.Syncd.KeysTest do
  use ExUnit.Case, async: true

  alias BaileysEx.Syncd.Keys

  # Deterministic 32-byte key material for all tests.
  @key_data :binary.copy(<<0xAB>>, 32)

  # Cross-language pinned vectors generated by Node.js crypto.hkdf with identical
  # parameters (HKDF-SHA256, salt=empty, info="WhatsApp Mutation Keys", len=160).
  # See dev/scripts/generate_syncd_vectors.mjs
  @pinned_index_key Base.decode16!(
                      "1A2F88AA8E3EB24CA402DB696DE12C1086A276ABDBA2C47E26C06364B93F3B3D"
                    )
  @pinned_value_encryption_key Base.decode16!(
                                 "77A7EC8C43ABB19447F8D835C13969879BD93002C98F26208D333F6F1CF164E6"
                               )
  @pinned_value_mac_key Base.decode16!(
                          "727F48E2DC0C564EF1AFDCC4970A7B33E2CF0755023A54C86B5E98EC87D95806"
                        )
  @pinned_snapshot_mac_key Base.decode16!(
                             "594042C35C7F491A06F8DB5700E83979B43731E1577AD5B1EBADF65777A0C974"
                           )
  @pinned_patch_mac_key Base.decode16!(
                          "1E554669BD64C63BFC9BAF191288AB37093C166447194DEFC98DE6C53D86FA9C"
                        )

  describe "expand_app_state_keys/1" do
    test "returns map with five 32-byte keys" do
      result = Keys.expand_app_state_keys(@key_data)

      assert byte_size(result.index_key) == 32
      assert byte_size(result.value_encryption_key) == 32
      assert byte_size(result.value_mac_key) == 32
      assert byte_size(result.snapshot_mac_key) == 32
      assert byte_size(result.patch_mac_key) == 32
    end

    test "all five keys are distinct" do
      result = Keys.expand_app_state_keys(@key_data)

      keys = [
        result.index_key,
        result.value_encryption_key,
        result.value_mac_key,
        result.snapshot_mac_key,
        result.patch_mac_key
      ]

      assert length(Enum.uniq(keys)) == 5
    end

    test "deterministic — same input always produces same output" do
      a = Keys.expand_app_state_keys(@key_data)
      b = Keys.expand_app_state_keys(@key_data)
      assert a == b
    end

    test "different inputs produce different outputs" do
      other = :binary.copy(<<0xCD>>, 32)
      a = Keys.expand_app_state_keys(@key_data)
      b = Keys.expand_app_state_keys(other)
      assert a.index_key != b.index_key
    end

    test "pinned vector — index_key matches Node.js HKDF output" do
      result = Keys.expand_app_state_keys(@key_data)
      assert result.index_key == @pinned_index_key
    end

    test "pinned vector — value_encryption_key matches Node.js HKDF output" do
      result = Keys.expand_app_state_keys(@key_data)
      assert result.value_encryption_key == @pinned_value_encryption_key
    end

    test "pinned vector — value_mac_key matches Node.js HKDF output" do
      result = Keys.expand_app_state_keys(@key_data)
      assert result.value_mac_key == @pinned_value_mac_key
    end

    test "pinned vector — snapshot_mac_key matches Node.js HKDF output" do
      result = Keys.expand_app_state_keys(@key_data)
      assert result.snapshot_mac_key == @pinned_snapshot_mac_key
    end

    test "pinned vector — patch_mac_key matches Node.js HKDF output" do
      result = Keys.expand_app_state_keys(@key_data)
      assert result.patch_mac_key == @pinned_patch_mac_key
    end
  end

  describe "mutation_keys/1" do
    test "is an alias for expand_app_state_keys/1" do
      assert Keys.mutation_keys(@key_data) == Keys.expand_app_state_keys(@key_data)
    end
  end
end
